import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "@/components/footer";
import Navbar1 from "@/components/navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`flex flex-col min-h-screen bg-cover bg-no-repeat bg-[url('https://res.cloudinary.com/da2aauwq2/image/upload/v1721525358/vintage_console_ok6qqm.png')] ${inter.className}`}>
        <header>
          <Navbar1 />
        </header>
        <main className="flex-grow">
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}


