import Head from 'next/head';
import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "@/components/footer";
import Navbar1 from "@/components/navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <Head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
        {/* Puedes agregar más meta tags aquí si es necesario */}
      </Head>
      <body className={`flex flex-col min-h-screen bg-cover bg-fixed bg-no-repeat bg-[url('https://res.cloudinary.com/da2aauwq2/image/upload/v1721598153/epic_body_2160_x_3840_px_4_dyb1kd.png')] sm:bg-[url('https://res.cloudinary.com/da2aauwq2/image/upload/v1721525358/vintage_console_ok6qqm.png')] ${inter.className}`}>
        <header>
          <Navbar1 />
        </header>
        <main className="flex-grow">
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}


